[os]
format = "[$symbol](bold white)"
disabled = false

[os.symbols]
Arch = "ğŸ—ï¸ "
Macos = "ğŸ "
Windows = "ğŸªŸ "

[directory]
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false
read_only = " ğŸ”’"

[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ—](bold red) '

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = "..."

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[time]
disabled = false
use_12hr = true
